import { convertItemUUID, reverseConvertUUID } from "./helpers.js";
import { system, anachronismsystem } from "./main.js";

export const DEITIES = {
    pf2e: {
        AAKRITI: { UUID: "Compendium.pf2e.deities.Item.0xCttKr5oqjirGCe", name: "Aakriti", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.3WAto1tsqHqgNoby", image: { source: "character-gallery", url: "modules/pf2e-tokens-characters/assets/tokens/aakriti.webp", dynamicurl: "modules/pf2e-tokens-characters/assets/subjects/aakriti.webp", scale: 1 } },
        ABADAR: { UUID: "Compendium.pf2e.deities.Item.d56paSkcwvll2OhR", name: "Abadar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.etnxC2suXGdbykxQ", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_abadar.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_abadar.webp", scale: 1 } },
        ACHAEKEK: { UUID: "Compendium.pf2e.deities.Item.51kMMWaT6CqpGlGk", name: "Achaekek", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.FU7Gz3fXhOj3Co4J", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_achaekek.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_achaekek.webp", scale: 2 } },
        ADANYE: { UUID: "Compendium.pf2e.deities.Item.gutbzYTZvRTnq4on", name: "Adanye", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.nch4XKlbTW2g1evC" },
        AHPOOK: { UUID: "Compendium.pf2e.deities.Item.dkKnv37c8RBPblgV", name: "Ah Pook", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.abZqx29yjiytQsse", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_ah-pook.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_ah-pook.webp", scale: 1 } },
        ALETH: { UUID: "Compendium.pf2e.deities.Item.2XM5clKBu67zJEwW", name: "Aleth", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.QBwfmI2hjbZQhB5u", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_aleth.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_aleth.webp", scale: 1 } },
        ALGLENWEIS: { UUID: "Compendium.pf2e.deities.Item.uXkMGx0OD896ZQlT", name: "Alglenweis", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.WsNUlMVi9qHZN8jG" },
        ALSETA: { UUID: "Compendium.pf2e.deities.Item.9n2CI0B3EA4y3BuU", name: "Alseta", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.vB5kAGLQcPSnq3wo", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_alseta.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_alseta.webp", scale: 1 } },
        ANGAZHAN: { UUID: "Compendium.pf2e.deities.Item.cHAbE86pto5bvIWo", name: "Angazhan", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.2X1bHnbRYn3738W1" },
        ANGRADD: { UUID: "Compendium.pf2e.deities.Item.Xb1N5YfxboJH26Jh", name: "Angradd", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.ks9gD4exPOD4PRHX" },
        APSU: { UUID: "Compendium.pf2e.deities.Item.o8ayCv3LAHWlu0vQ", name: "Apsu", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.inUeeUTxnCpU80kn", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_apsu.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_apsu.webp", scale: 2 } },
        ARAZNI: { UUID: "Compendium.pf2e.deities.Item.HtRxo4J3elFteIqu", name: "Arazni", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.5lHIGgiJ2sEKTCrX", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_arazni.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_arazni.webp", scale: 1 } },
        ARQUEROS: { UUID: "Compendium.pf2e.deities.Item.akcmQbvNWfhEfEhf", name: "Arqueros", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.9otbOJnRGUOFLntf", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9312_arqueros.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9312_arqueros.webp", scale: 2 } },
        ARSHEA: { UUID: "Compendium.pf2e.deities.Item.KDFujU3Yug6AwCOz", name: "Arshea", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.fIsVlHEhvrRuJ6WG" },
        ARUNDHAT: { UUID: "Compendium.pf2e.deities.Item.jrPmEfubRDzMKbxl", name: "Arundhat", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.Nl2tBWmfnRg6AKVI" },
        ASMODEUS: { UUID: "Compendium.pf2e.deities.Item.QRkcFciCOmFoxF1B", name: "Asmodeus", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.8LwkDyaCUjpp6nnb", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_asmodeus.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_asmodeus.webp", scale: 1 } },
        ATREIA: { UUID: "Compendium.pf2e.deities.Item.R0DvoLO8WbYIYhb3", name: "Atreia", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.v6kvW30VogtPyVBN" },
        ATROGINE: { UUID: "Compendium.pf2e.deities.Item.ChiKlaNDNYgGqtF7", name: "Atrogine", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.T2erXp4niO0iNDQp", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_atrogine.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_atrogine.webp", scale: 2 } },
        AYRZUL: { UUID: "Compendium.pf2e.deities.Item.aChBtIDfA59QQ7SN", name: "Ayrzul", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.LGgcu3R4wIFNszTT" },
        BAEKHO: { UUID: "Compendium.pf2e.deities.Item.cSakUTwOtxe6Y0rH", name: "Baekho", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.fxQ9LqVVl1M67Kwx" },
        BALUMBDAR: { UUID: "Compendium.pf2e.deities.Item.1fmTXGRPa8fLXZKL", name: "Balumbdar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.kkO2M28D7tQfrJZ1" },
        BERGELMIR: { UUID: "Compendium.pf2e.deities.Item.30uY6NkhYmPI3Oii", name: "Bergelmir", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.MY0ZvD2uaatopy6E", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_bergelmir.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_bergelmir.webp", scale: 1 } },
        BESMARA: { UUID: "Compendium.pf2e.deities.Item.wkDOeK7ENz1ra8IC", name: "Besmara", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.u2RAcpOdHAnOgdLB", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_besmara.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_besmara.webp", scale: 2 } },
        BOLKA: { UUID: "Compendium.pf2e.deities.Item.HD7g8T8ioy1EH3M8", name: "Bolka", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.vJCUbCCZRdpjIvVO" },
        BRIGH: { UUID: "Compendium.pf2e.deities.Item.vEMCpm7iidycRT5D", name: "Brigh", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.newFTkBZZmXVMOSH", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_brigh.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_brigh.webp", scale: 2 } },
        CALISTRIA: { UUID: "Compendium.pf2e.deities.Item.AlL9GtlTldbqNoVm", name: "Calistria", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.ZJDSKtQ6PpXGZjw6", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_calistria.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_calistria.webp", scale: 1 } },
        CAMAZOTZ: { UUID: "Compendium.pf2e.deities.Item.Byw9omVSNwYKcauw", name: "Camazotz", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.6aF4bhL9bWSF20mi", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_camazotz.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_camazotz.webp", scale: 2 } },
        CASANDALEE: { UUID: "Compendium.pf2e.deities.Item.soiVh53y9RAeSLEk", name: "Casandalee", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.ytPoSI1DJoXSoiwx", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_casandalee.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_casandalee.webp", scale: 2 } },
        CAYDENCAILEAN: { UUID: "Compendium.pf2e.deities.Item.v67fHklTZ6LoU54q", name: "Cayden Cailean", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.dHrz9yBTBQKwFKey", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_cayden-cailean.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_cayden-cailean.webp", scale: 2 } },
        CHALDIRA: { UUID: "Compendium.pf2e.deities.Item.4GO4iT585ynLJnc8", name: "Chaldira", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.mcqnG9AJK0pRS22f", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_chaldira zuzaristan.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_chaldira zuzaristan.webp", scale: 2 } },
        CHAMIDU: { UUID: "Compendium.pf2e.deities.Item.yiKle2URZ43KYVKQ", name: "Chamidu", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.CsqqAvLTBCJxO20g" },
        CHOHAR: { UUID: "Compendium.pf2e.deities.Item.OlVCyRgOaPJji4qt", name: "Chohar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.vRBr0DriwOXZlKWF" },
        DAHAK: { UUID: "Compendium.pf2e.deities.Item.Bzfc5mIUfMxOnQWu", name: "Dahak", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.urmG8YZF4qcrR4FR", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_dahak.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_dahak.webp", scale: 3 } },
        DAIKITSU: { UUID: "Compendium.pf2e.deities.Item.M3eb94Nd6uXti2IK", name: "Daikitsu", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.dVKTT8Mqp8Oyi6cy", image: { source: "character-gallery", url: "modules/pf2e-tokens-characters/assets/tokens/daikitsu.webp", dynamicurl: "modules/pf2e-tokens-characters/assets/subjects/daikitsu.webp", scale: 1 } },
        DAJERMUBE: { UUID: "Compendium.pf2e.deities.Item.XaaDDVS4sEJd4m99", name: "Dajermube", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.YIUenWegXpWBhUpz", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_dajermube.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_dajermube.webp", scale: 1 } },
        DESNA: { UUID: "Compendium.pf2e.deities.Item.JgqH3BhuEuA4Zyqs", name: "Desna", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.uBmWoNQTPEqpGrCe", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_desna.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_desna.webp", scale: 2 } },
        DIOMAZUL: { UUID: "Compendium.pf2e.deities.Item.XHDlP7o1jNz9851v", name: "Diomazul", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.uaLpFfdvDwDtnGxc" },
        DRANNGVIT: { UUID: "Compendium.pf2e.deities.Item.oyp2E685VsQFKMXi", name: "Dranngvit", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.UGOVaJbbzmG0iG4s" },
        DROSKAR: { UUID: "Compendium.pf2e.deities.Item.39z55kowQFOUH2v0", name: "Droskar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.80Z1LkOsV53JxRrh" },
        EMBARAL: { UUID: "Compendium.pf2e.deities.Item.hDNLCRnDjYqmPYv6", name: "Embaral", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.MlbuFR5xlx9MA4p3", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_embaral.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_embaral.webp", scale: 1 } },
        EMMETONGALARDARIA: { UUID: "Compendium.pf2e.deities.Item.K4s8a6gI1OmuWhMk", name: "Emmeton Galardaria", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.9Q4LDJHg7f4moyBN", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_emmeton galadaria.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_emmeton galadaria.webp", scale: 2 } },
        ERASTIL: { UUID: "Compendium.pf2e.deities.Item.mm1j6UbHqFCI8fwB", name: "Erastil", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.Cq39VSaBGWJqTdjv", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_erastil.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_erastil.webp", scale: 2 } },
        FALAYNA: { UUID: "Compendium.pf2e.deities.Item.IXLzDSMGndFb5rGY", name: "Falayna", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.8DHviPprJXMk1iDi", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9312_falayna.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9312_falayna.webp", scale: 2 } },
        FANDARRA: { UUID: "Compendium.pf2e.deities.Item.9vcKBv8h5vugb8lL", name: "Fandarra", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.OiDJ3IRPZuX5R0WN" },
        FERRUMNESTRA: { UUID: "Compendium.pf2e.deities.Item.RnS5P7zX0HRPsDnt", name: "Ferrumnestra", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.1KZtOrPLEWtZad5I" },
        FINDELADLARA: { UUID: "Compendium.pf2e.deities.Item.0BH54ZVR8NcrGlMu", name: "Findeladlara", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.f4WI8aIG4pKoV5sP" },
        FOLGRIT: { UUID: "Compendium.pf2e.deities.Item.VEyowuhC4FsBnG8c", name: "Folgrit", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.a97yfzIOpv4me0ad" },
        FUMEIYOSHI: { UUID: "Compendium.pf2e.deities.Item.6O4UGWcYERDEugzk", name: "Fumeiyoshi", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.2MMBSFRK7koBXFEk" },
        GENDOWYN: { UUID: "Compendium.pf2e.deities.Item.3ffVxwgtvR1imHm8", name: "Gendowyn", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.JIYdZwFM8mULlamp", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9312_gendowyn.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9312_gendowyn.webp", scale: 2 } },
        GENERALSUSUMU: { UUID: "Compendium.pf2e.deities.Item.Zi1UARhode3FSFLr", name: "General Susumu", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.nTuYzRVNzgyNZRe8" },
        GENZAERI: { UUID: "Compendium.pf2e.deities.Item.auHS1P7mXJjO2QlY", name: "Genzaeri", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.gbVAouK0Oasc7YcK", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_genzaeri.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_genzaeri.webp", scale: 1 } },
        GHLAUNDER: { UUID: "Compendium.pf2e.deities.Item.oRvuLq3o2FxXizt9", name: "Ghlaunder", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.MpvGMz9LOYHzsCN6", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_ghlaunder.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_ghlaunder.webp", scale: 2 } },
        GORUM: { UUID: "Compendium.pf2e.deities.Item.88vRw2ZVPax4hhga", name: "Gorum", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.RBDKnfjZ98Nz8jLf", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_gorum.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_gorum.webp", scale: 2 } },
        GOZREH: { UUID: "Compendium.pf2e.deities.Item.swwwP7eVmlNuWTb7", name: "Gozreh", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.fbuxTcpKDSgJA6pc", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_gozreh.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_gozreh.webp", scale: 2 } },
        GRANDMOTHERSPIDER: { UUID: "Compendium.pf2e.deities.Item.fuPTR1laXO6EionS", name: "Grandmother Spider", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.4ielnNjOT6AiXyTr", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_grandmother spider.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_grandmother spider.webp", scale: 2 } },
        GROETUS: { UUID: "Compendium.pf2e.deities.Item.WloVxo6HXJdS4YTt", name: "Groetus", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.QbzhArc1zrvW7kUk", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_groetus.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_groetus.webp", scale: 1 } },
        GRUHASTHA: { UUID: "Compendium.pf2e.deities.Item.tcvobm8O84qv0aO5", name: "Gruhastha", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.rtyL4qO4xBUICYZm", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_gruhastha.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_gruhastha.webp", scale: 2 } },
        GRUNDINNAR: { UUID: "Compendium.pf2e.deities.Item.tk7gRxXsqvBwQrUF", name: "Grundinnar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.7UK5DdSX8pu9rscB" },
        HANSPUR: { UUID: "Compendium.pf2e.deities.Item.QlDnoOwf0PppymTn", name: "Hanspur", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.sadbkTqsDWE6DStC", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_hanspur.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_hanspur.webp", scale: 2 } },
        HEIFENG: { UUID: "Compendium.pf2e.deities.Item.DEKKbg6riAdL2ARf", name: "Hei Feng", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.gIwZAECzovIE43jF", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_hei feng.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_hei feng.webp", scale: 2 } },
        HSHURHA: { UUID: "Compendium.pf2e.deities.Item.A37XqON6QRPzQhp7", name: "Hshurha", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.bqQMOwA0OhRB4JiX" },
        IMMONHIEL: { UUID: "Compendium.pf2e.deities.Item.smGfeOk8Jgcz0Qkv", name: "Immonhiel", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.5GaVjJjHJMYOfHjr" },
        IOMEDAE: { UUID: "Compendium.pf2e.deities.Item.eErEiVmBqltYXFJ6", name: "Iomedae", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.624XjR5ajkJwULEu", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_iomedae.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_iomedae.webp", scale: 1 } },
        IRORI: { UUID: "Compendium.pf2e.deities.Item.qqqrbq4uCrelQvgH", name: "irori", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.N45Z6J37sw4yXdX6", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_irori.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_irori.webp", scale: 2 } },
        IZUYAKU: { UUID: "Compendium.pf2e.deities.Item.LJr99kbbzzgh4IZm", name: "Izuyaku", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.CItGuRjr9pVsWyW7", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_izuyaku.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_izuyaku.webp", scale: 2 } },
        JINLI: { UUID: "Compendium.pf2e.deities.Item.w9vtltygWNG4eZDR", name: "Jin Li", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.G0aksa138wiYe7Se" },
        KALDEMASH: { UUID: "Compendium.pf2e.deities.Item.hLq1IF3mT8zOfUaE", name: "Kaldemash", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.36ToA6s11zTxq8bt", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_kaldemash.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_kaldemash.webp", scale: 2 } },
        KALEKOT: { UUID: "Compendium.pf2e.deities.Item.kiTcZxmKxGPCwDpg", name: "Kalekot", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.6d2QsuhP8ORwjWZi" },
        KAZUTAL: { UUID: "Compendium.pf2e.deities.Item.iXvyp9rGnqvFfy4q", name: "Kazutal", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.7RvZkV7mfkHfNFwk", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_kazutal.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_kazutal.webp", scale: 2 } },
        KELIZANDRI: { UUID: "Compendium.pf2e.deities.Item.14GLsVobnZTEmJrs", name: "Kelizandri", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.jZjRYAiFEVEB2z87" },
        KOFUSACHI: { UUID: "Compendium.pf2e.deities.Item.AIcDyoff265z9285", name: "Kofusachi", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.yDtFLh4mi9lsBJyL", image: { source: "character-gallery", url: "modules/pf2e-tokens-characters/assets/tokens/kofusachi.webp", dynamicurl: "modules/pf2e-tokens-characters/assets/tokens/kofusachi.webp", scale: 1 } },
        KOLS: { UUID: "Compendium.pf2e.deities.Item.zhPhYge7VJbIlJvA", name: "Kols", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.JufrU8eXfxy9drHI", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9312_kols.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9312_kols.webp", scale: 1 } },
        KURGESS: { UUID: "Compendium.pf2e.deities.Item.r5vooG7NfvA9prJK", name: "Kurgess", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.cfNPq3hlLdelWm71", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_kurgess.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_kurgess.webp", scale: 1 } },
        LADYJINGXI: { UUID: "Compendium.pf2e.deities.Item.xu05XGotyT5st56H", name: "Lady Jingxi", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.2N6s9l6IDxpZVABF", image: { source: "character-gallery", url: "modules/pf2e-tokens-characters/assets/tokens/lady-jingxi.webp", dynamicurl: "modules/pf2e-tokens-characters/assets/tokens/lady-jingxi.webp", scale: 1 } },
        LADYNANBYO: { UUID: "Compendium.pf2e.deities.Item.r6SFB1PzKsagDXff", name: "Lady Nanbyo", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.XS1nBv88jxWLAFsL", image: { source: "", url: "", dynamicurl: "", scale: 1 } },
        LAMASHTU: { UUID: "Compendium.pf2e.deities.Item.aipkJQxP4GBsTaGq", name: "Lamashtu", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.S7jAME9pCcycJs3Q", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_lamashtu.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_lamashtu.webp", scale: 2 } },
        LAOSHUPO: { UUID: "Compendium.pf2e.deities.Item.MbJ93Nw39h2cBYi5", name: "Lao Shu Po", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.Duu9JNxJmFUxRqLK" },
        LAUDINMIO: { UUID: "Compendium.pf2e.deities.Item.xLbSMedLDFyb8sFw", name: "Laudinmio", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.T2RP0KVwCmMAoYeA" },
        LIKHA: { UUID: "Compendium.pf2e.deities.Item.lUFMwdv1UOyzFhIM", name: "Likha", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.NFWSvrXRKGfOXmEm" },
        LUBAIKO: { UUID: "Compendium.pf2e.deities.Item.CnDEoo6WruQCXo1o", name: "Lubaiko", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.osyVRNRo7hYJAQie", image: { source: "character-gallery", url: "modules/pf2e-tokens-characters/assets/tokens/lubaiko.webp", dynamicurl: "modules/pf2e-tokens-characters/assets/subjects/lubaiko.webp", scale: 1 } },
        LUHAR: { UUID: "Compendium.pf2e.deities.Item.ub0PJ5QkrdoGzzb2", name: "Luhar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.d1XAEu1QOTmnbLr6" },
        LYSIANASSA: { UUID: "Compendium.pf2e.deities.Item.SCMlQDcoU1QcF3AS", name: "Lysianassa", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.W6XRNzpebdbjPLFA" },
        MAGRIM: { UUID: "Compendium.pf2e.deities.Item.nsiDGdgbAzkTQzOt", name: "Magrim", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.35npVQ0ShHYVpuqB", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo92112_magrim.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo92112_magrim.webp", scale: 1 } },
        MAHATHALLAH: { UUID: "Compendium.pf2e.deities.Item.Af4TSJjutVi9Vdwi", name: "Mahathallah", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.ynANoIFQVw9cam2Z" },
        MARISHI: { UUID: "Compendium.pf2e.deities.Item.9LwncUwHbG1f6qIt", name: "Marishi", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.p3N2ywCGgZ0akCJr" },
        MAZLUDEH: { UUID: "Compendium.pf2e.deities.Item.v1fsLP6nTkiy5ghB", name: "Mazludeh", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.FzgLGNNrkdyf98qR" },
        MILANI: { UUID: "Compendium.pf2e.deities.Item.fTJLgTfEMZreJ19r", name: "Milani", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.qSdYQH0vHnZVnqck", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_milani.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_milani.webp", scale: 2 } },
        MUGURANRITHU: { UUID: "Compendium.pf2e.deities.Item.omUWo1TQ6PDm5oeW", name: "Mugura and Nrithu", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.wNOFtokxChuNGFoX" },
        NALINIVATI: { UUID: "Compendium.pf2e.deities.Item.gsFaxWHbZmc1moY6", name: "Nalinivati", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.OyjeaF8H8jpaWab1" },
        NARAKAAS: { UUID: "Compendium.pf2e.deities.Item.hhV2g6aU8jKLEca1", name: "Narakaas", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.fkKoCNdZ1vUJzkat" },
        NETHYS: { UUID: "Compendium.pf2e.deities.Item.9EKyWmjLUu42evxC", name: "Nethys", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.c5BEy8BLZQYXiv1P", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_nethys.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_nethys.webp", scale: 2 } },
        NG: { UUID: "Compendium.pf2e.deities.Item.RzTd9PmgnfHNlFVf", name: "Ng", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.vwfrqsrkxptPUPbo" },
        NIN: { UUID: "Compendium.pf2e.deities.Item.4HJKRGYIVKeUdOwf", name: "Nin", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.xd4tjk7TB2PW2jra", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_nin.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_nin.webp", scale: 1 } },
        NIVIRHOMBODAZZLE: { UUID: "Compendium.pf2e.deities.Item.Mv6uTJLh3VGEoGLH", name: "Nivi Rhombodazzle", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.67FAwchedqYNnq5f", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_nivi rhombodazzle.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_nivi rhombodazzle.webp", scale: 1 } },
        NOCTICULA: { UUID: "Compendium.pf2e.deities.Item.jL1qiVOZBKXETtVD", name: "Nocticula", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.brzjZ7hJm3WRMVv3", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_nocticula.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_nocticula.webp", scale: 1 } },
        NORGORBER: { UUID: "Compendium.pf2e.deities.Item.GX6PF9ifR47Xyjg9", name: "Norgorber", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.PSoOLwuecMqnr8Cg", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_norgorber.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_norgorber.webp", scale: 2 } },
        OBARI: { UUID: "Compendium.pf2e.deities.Item.8hsVGRyq0dKMwwXT", name: "Obari", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.Dp3Sx0HF9CiHUuM4", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_obari.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_obari.webp", scale: 1 } },
        PHARASMA: { UUID: "Compendium.pf2e.deities.Item.QZD0u1jxwz0kj8uI", name: "Pharasma", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.ePpD31ZFCsp0UQyB", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_pharasma.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_pharasma.webp", scale: 2 } },
        PHIDEVA: { UUID: "Compendium.pf2e.deities.Item.0EXQHfNN11AfDqNm", name: "Phi Deva", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.Cneqj99rVkFRwKAp" },
        PICOPERI: { UUID: "Compendium.pf2e.deities.Item.CeBP002LcMfqgIRl", name: "Compendium.pf2e.deities.Item.CeBP002LcMfqgIRl", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.wwiyrhr2gCxUIru1" },
        QIZHONG: { UUID: "Compendium.pf2e.deities.Item.giAsBYiL2omr0x2L", name: "Qi Zhong", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.ka3PDdHgAJMQg5yr" },
        RAGATHIEL: { UUID: "Compendium.pf2e.deities.Item.GEBaoeiv5CB9h2Bn", name: "Ragathiel", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.UUQPHzPGYrto9HFC", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9312_ragathiel.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9312_ragathiel.webp", scale: 3 } },
        RAGDYA: { UUID: "Compendium.pf2e.deities.Item.o9tK1T28LNEVzpFV", name: "Ragdya", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.vwbYIgPPMkPYninl", image: { source: "character-gallery", url: "modules/pf2e-tokens-characters/assets/tokens/ragdya.webp", dynamicurl: "modules/pf2e-tokens-characters/assets/subjects/ragdya.webp", scale: 1 } },
        RANGINORI: { UUID: "Compendium.pf2e.deities.Item.Ij1KRM8ufkEjGnR3", name: "Ranginori", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.28am0U2RRCzHm8oe", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_ranginori.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_ranginori.webp", scale: 1 } },
        RAVITHRA: { UUID: "Compendium.pf2e.deities.Item.1nQVLOyWv5kC0bCU", name: "Ravithra", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.mnaIbKgzA8yaBaCx" },
        ROVAGUG: { UUID: "Compendium.pf2e.deities.Item.Bhxji0kxIbMKqdkw", name: "Rovagug", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.sT7SEKgyqyT7TwSD", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_rovagug.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_rovagug.webp", scale: 2 } },
        ROWDROSH: { UUID: "Compendium.pf2e.deities.Item.44fcXgp3fnkoyb4R", name: "Rowdrosh", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.eCA6Rw7oUQL6sDOR" },
        SAIRAZUL: { UUID: "Compendium.pf2e.deities.Item.1NxkZf6ndijKeufX", name: "Sairazul", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.XqnGQydRSznRYRjT" },
        SARENRAE: { UUID: "Compendium.pf2e.deities.Item.BNycwu3I21dTh4D9", name: "Sarenrae", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.uzCWZqNEQj0WT90k", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_sarenrae.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_sarenrae.webp", scale: 3 } },
        SHELYN: { UUID: "Compendium.pf2e.deities.Item.gxwmzxUWBOhdgFSN", name: "Shelyn", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.3igZVjO4QIncQA7G", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_shelyn.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_shelyn.webp", scale: 1 } },
        SHIZURU: { UUID: "Compendium.pf2e.deities.Item.s9opv94lGDRKnw6W", name: "Shizuru", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.sZfXW1J8RlW8RiBh", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_shizuru.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_shizuru.webp", scale: 1 } },
        SHUMUNUE: { UUID: "Compendium.pf2e.deities.Item.hAoVzkeFjTwh5Ykl", name: "Shumunue", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.chWtwGSMg5VpXYAy" },
        SIVANAH: { UUID: "Compendium.pf2e.deities.Item.iJyhAFmHOLZBvWnJ", name: "Sivanah", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.f84ARl8v4F4YPDRg", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_sivanah.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_sivanah.webp", scale: 1 } },
        SKODE: { UUID: "Compendium.pf2e.deities.Item.IK2AL3bL6htrrnnC", name: "Skode", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.zQCbvkWsWs0G4aSJ" },
        SRIKALISSRITAMINGSRIBARIL: { UUID: "Compendium.pf2e.deities.Item.ox0AaGLIyzCUrre2", name: "Srikalis, Sritaming, and Sribaril", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.6PPwiiSv6A7Kw9cy" },
        SUNWUKONG: { UUID: "Compendium.pf2e.deities.Item.BLNXYqvzmLgjMq2p", name: "Sun Wukong", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.SOo2Zk4ZSn2YhKsa" },
        SUYUDDHA: { UUID: "Compendium.pf2e.deities.Item.u2tnG7fKkZ2KHMcT", name: "Suyuddha", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.9MItnpCjdOZ9Ukdm", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9312_suyuddha.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9312_suyuddha.webp", scale: 2 } },
        TANAGAAR: { UUID: "Compendium.pf2e.deities.Item.DFxbPmQLOqcmbPTz", name: "Tanagaar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.2WCCNRfL0iQv7ZKe" },
        THEDEVOURER: { UUID: "Compendium.pf2e.deities.Item.Iwgr8NVomfEuX4WR", name: "The Devourer", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.3f34NJdzaUeKZC5a", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_devourer.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_devourer.webp", scale: 1 } },
        THELADYOFTHENORTHSTAR: { UUID: "Compendium.pf2e.deities.Item.JzaazIXXvAW02Cip", name: "The Lady of the North Star", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.IJrEdnXMB6rTmEu1" },
        THISAMET: { UUID: "Compendium.pf2e.deities.Item.m6UYxDnwGkOo8IY5", name: "Thisamet", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.QMSZ5gydWHSEfCNL" },
        TLEHAR: { UUID: "Compendium.pf2e.deities.Item.0R2BjVb7d9tYCIbk", name: "Tlehar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.ykwhVQreh0EdPYSJ" },
        TORAG: { UUID: "Compendium.pf2e.deities.Item.sZrdzh0ANQnZGXJb", name: "Torag", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.CCsr7VapUd5evHGj", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_torag.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_torag.webp", scale: 2 } },
        TREERAZER: { UUID: "Compendium.pf2e.deities.Item.ENzMYuzBZGIujSMx", name: "Treerazer", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.VtLDTtYg75r0Uz5b", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_treerazer.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_treerazer.webp", scale: 2 } },
        TRUDD: { UUID: "Compendium.pf2e.deities.Item.N8a76dkGfUvxvSW0", name: "Trudd", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.I3Rr86j5NyXc9qEZ" },
        TSUKIYO: { UUID: "Compendium.pf2e.deities.Item.aTYy1WHwAZiuei4h", name: "Tsukiyo", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.MgN4cHXCpZtGdRHn", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_tsukiyo.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_tsukiyo.webp", scale: 2 } },
        URGATHOA: { UUID: "Compendium.pf2e.deities.Item.22n3N47sqbqbDxbp", name: "Urgathoa", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.URvKrowmxprOoz2o", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_urgathoa.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_urgathoa.webp", scale: 1 } },
        UVUKO: { UUID: "Compendium.pf2e.deities.Item.w4fDrwL8VIqJDPfR", name: "Uvuko", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.TZ08ahP8l4npr59U" },
        VERILORN: { UUID: "Compendium.pf2e.deities.Item.pafYqAGj47TmGBib", name: "Verilorn", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.4DKRzBVNsayyLEpU" },
        VILDEIS: { UUID: "Compendium.pf2e.deities.Item.y93whGnGZjFyw5A0", name: "Vildeis", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.3ye4VMfrVoD3PYkz", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9312_vildeis.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9312_vildeis.webp", scale: 3 } },
        VINESHVAKHI: { UUID: "Compendium.pf2e.deities.Item.d47XTSODGAKANu3d", name: "Vineshvakhi", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.V695cssut3SwU9Ki" },
        VUDRAVATI: { UUID: "Compendium.pf2e.deities.Item.JMRGy8Fb1ZYeSbcK", name: "Vudravati", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.dPyL1wt8IVQ3pn0n", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_vudravati.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_vudravati.webp", scale: 2 } },
        WALKENA: { UUID: "Compendium.pf2e.deities.Item.g1AVEGi8QibhS007", name: "Walkena", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.4fQvCSKqkfh2UpjP", image: { source: "character-gallery", url: "modules/pf2e-tokens-characters/assets/tokens/walkena-throne.webp", dynamicurl: "modules/pf2e-tokens-characters/assets/subjects/walkena-throne.webp", scale: 1 } },
        YAEZHING: { UUID: "Compendium.pf2e.deities.Item.83jKKHQPoqVylmrF", name: "Yaezhing", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.baApEfGyT3DhG82A", image: { source: "", url: "", dynamicurl: "", scale: 1 } },
        YAMATSUMI: { UUID: "Compendium.pf2e.deities.Item.tb0oADxOoMhyrYRA", name: "Yamatsumi", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.gpWxsFBrMd0x4OwU" },
        YELAYNE: { UUID: "Compendium.pf2e.deities.Item.1xG0PDxn0rhmJhMS", name: "Yelayne", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.0iPnHKKHPk9UB0Us" },
        YMERI: { UUID: "Compendium.pf2e.deities.Item.7L9KIqixgseSCY3X", name: "Ymeri", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.b2bVWt3ZBC7gnT5p" },
        ZJARTOVAN: { UUID: "Compendium.pf2e.deities.Item.kBuCFUp4KYJEnMLk", name: "Zjar-Tovan", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.Za2h09yVUk0FGzSb", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_zjar tovan.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_zjar tovan.webp", scale: 2 } },
        ZONKUTHON: { UUID: "Compendium.pf2e.deities.Item.ZfN7jkK6boU1FuiS", name: "Zon-Kuthon", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.prr07FPqtJcQ2L5B", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_zon-kuthon.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_zon-kuthon.webp", scale: 2 } },
        ZURA: { UUID: "Compendium.pf2e.deities.Item.8ZSywyo8YQPduo92", name: "Zura", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.8www6oEJVMNmbxA3" },
        ZYPHUS: { UUID: "Compendium.pf2e.deities.Item.LLMTMgARSTlO7S9U", name: "Zyphus", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.TfT7hugocr5dR7FJ", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_zyphus.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_zyphus.webp", scale: 2 } }
    },
    sf2e: {
        ABADAR: { UUID: "Compendium.pf2e.deities.Item.d56paSkcwvll2OhR", name: "Abadar", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.IALvDynB1vvF1oIT", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_abadar.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_abadar.webp", scale: 1 } },
        BESMARA: { UUID: "Compendium.pf2e.deities.Item.wkDOeK7ENz1ra8IC", name: "Besmara", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.PNt7fORlAdz8oE70", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_besmara.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_besmara.webp", scale: 2 } },
        DAMORITOSH: { UUID: "Compendium.sf2e-anachronism.deities.Item.fjisjygyebkfu9pN", name: "Damoritosh", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.3q3X9XoyqpghfRqX" },
        ELORITU: { UUID: "Compendium.sf2e-anachronism.deities.Item.N1eCNDynvJFIl154", name: "Eloritu", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.uC1JrYZTYoHQF71I" },
        HYLAX: { UUID: "Compendium.sf2e-anachronism.deities.Item.fyVrRIME5ruQ61S9", name: "Hylax", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.uQNNAxJv3QMH5p0t" },
        IBRA: { UUID: "Compendium.sf2e-anachronism.deities.Item.VIrT7AMlWHNOlgPs", name: "Ibra", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.vJ4CXdWd0CeYr5p3" },
        LAMBATUIN: { UUID: "Compendium.sf2e-anachronism.deities.Item.o9dgag7sAiFUnN9I", name: "Lambatuin", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.hJ07scDbWYaZHInn" },
        LAOSHUPO: { UUID: "Compendium.pf2e.deities.Item.MbJ93Nw39h2cBYi5", name: "Lao Shu Po", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.wBpvKJptTCFvmbkH" },
        LISSALA: { UUID: "Compendium.pf2e.deities.Item.w66gCNiZ7dslqG8K", name: "Lissala", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.DDE15B7bIhuEoFlY" },
        MEYEL: { UUID: "Compendium.sf2e-anachronism.deities.Item.8KdiTOuKttm4njGx", name: "Meyel", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.eGd7cUQj3CYHzFUo" },
        ORAS: { UUID: "Compendium.sf2e-anachronism.deities.Item.5uQoTXSUuoJv1VMt", name: "Oras", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.K2iZS3mkCQp2WEK1" },
        PHARASMA: { UUID: "Compendium.pf2e.deities.Item.QZD0u1jxwz0kj8uI", name: "Pharasma", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.eGXbHrZkNED4k8Mb", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_pharasma.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_pharasma.webp", scale: 2 } },
        TALAVET: { UUID: "Compendium.sf2e-anachronism.deities.Item.CYUkMkhXSnZPLLhr", name: "Talavet", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.vxJa7i5k8eVc2C6S" },
        THEDEVOURER: { UUID: "Compendium.pf2e.deities.Item.Iwgr8NVomfEuX4WR", name: "The Devourer", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.4O8JzlWhz9elLRqu", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo13003_devourer.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo13003_devourer.webp", scale: 1 } },
        THENEWBORN: { UUID: "Compendium.sf2e-anachronism.deities.Item.frkwaiKRQnE8s5QQ", name: "The Newborn", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.udVWBbgHP58YRhQK" },
        TRIUNE: { UUID: "Compendium.sf2e-anachronism.deities.Item.OSQPUVZrtxJUisPa", name: "Triune", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.btZ7hNDqtfvVqkvQ" },
        URGATHOA: { UUID: "Compendium.pf2e.deities.Item.22n3N47sqbqbDxbp", name: "Urgathoa", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.g0XoHElqRT3ZwXJ2", image: { source: "myth-and-magic", url: "modules/pf2e-tokens-myth-and-magic/assets/tokens/pzo9303_urgathoa.webp", dynamicurl: "modules/pf2e-tokens-myth-and-magic/assets/subjects/pzo9303_urgathoa.webp", scale: 1 } },
        WEYDAN: { UUID: "Compendium.sf2e-anachronism.deities.Item.hrqNoz1QiA6z9LMV", name: "Weydan", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.G47qEAF6JpAAWF7j" },
        YARAESA: { UUID: "Compendium.sf2e-anachronism.deities.Item.YiV6Wd2OxCOxy00A", name: "Yaraesa", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.foyK3xZDswPWSeQg" },
        ZONSHELYN: { UUID: "Compendium.sf2e-anachronism.deities.Item.P8SXe1RC7PTR2384", name: "Zon-Shelyn", avatarUUID: "Compendium.pf2e-avatars.avatars.Item.dhZri1XkOqjEkaRG" }
    }
};

export function getDeity(deityUUID){    
    let deity = Object.values(DEITIES[system]).find(p => p.UUID == convertItemUUID(deityUUID, system=="sf2e" && p.UUID.includes('.sf2e-anachronism.')));
    const fromSystem = !!deity;
    if (!deity) 
        deity = Object.values(DEITIES[anachronismsystem]).find(p => p.UUID == convertItemUUID(deityUUID, system=="sf2e" && p.UUID.includes('.sf2e-anachronism.')));
    if (!deity)    
        return null;
    
    const result = structuredClone(deity);
    result.UUID = reverseConvertUUID(deity.UUID, fromSystem);
    result.avatarUUID = reverseConvertUUID(deity.avatarUUID);
    return result;
}

export function getDeityByAvatar(avatarUUID){
    let deity = Object.values(DEITIES[system]).find(p => p.avatarUUID == convertItemUUID(avatarUUID));
    const fromSystem = !!deity;   
    if (!deity)
        deity = Object.values(DEITIES[anachronismsystem]).find(p => p.avatarUUID == convertItemUUID(avatarUUID));

    if (!deity)
        return null;

    const result = structuredClone(deity);
    result.UUID = reverseConvertUUID(deity.UUID, fromSystem);
    result.avatarUUID = reverseConvertUUID(deity.avatarUUID);
    return result;
}

